created_at: '2025-08-29T02:20:50.818900'
frequency_penalty: 0.0
max_history_size: 1000
max_tokens: 32768
model: gpt-4.1-mini
presence_penalty: 0.0
response_format: text
stream: true
system_prompt: null
temperature: 1.0
top_p: 1.0
updated_at: '2025-08-29T02:20:50.818904'
